name: modelwarehouse_venv

channels:  
  - conda-forge
  - defaults

dependencies:
  - python>=3.12
  - pip
  - pandas
  - numpy
  - seaborn
  - btrees
  - persistent
  - transaction
  - zodb
  - zconfig
  - python-dotenv
  - pip:
    - relstorage
